### ISSUE TITLE
Usage?

### ISSUE THREAD

**Issue by edword** [marudor/inline-css-loader#1]
Hey, this loader looks great and definitely interested in using it! Curious how one would go about using it? 

Thanks!!

**Comment by marudor** [comment]
Just add it as a loader after babel. (Babel has to be before this loader in the chain.)
for instance:
```
{ test: /\.CSS.js$/, exclude: /(node_modules|dependency)/, loader: 'inline-css!babel' }
```

This basically runs alls .CSS.js files through this loader. (Other files should not be run though the loader)
